# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_userinfo_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
