# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_searchinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchinfo',
            name='searchTime',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
