# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_searchinfo_searchtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=50)),
                ('fileId', models.IntegerField()),
            ],
        ),
    ]
