# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_taginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInfo',
        ),
    ]
