# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_delete_taginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
