# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0009_auto_20170109_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
