# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0010_auto_20170202_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchinfo',
            name='mSearchCount',
            field=models.IntegerField(default=0),
        ),
    ]
